// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: blocktrace.proto

package blocktrace

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlockTraceStreamServer_StreamBlockTraceData_FullMethodName = "/com.bloxroute.bsc.mev.blocktrace.BlockTraceStreamServer/StreamBlockTraceData"
)

// BlockTraceStreamServerClient is the client API for BlockTraceStreamServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC service definition
type BlockTraceStreamServerClient interface {
	StreamBlockTraceData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error)
}

type blockTraceStreamServerClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockTraceStreamServerClient(cc grpc.ClientConnInterface) BlockTraceStreamServerClient {
	return &blockTraceStreamServerClient{cc}
}

func (c *blockTraceStreamServerClient) StreamBlockTraceData(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Block], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlockTraceStreamServer_ServiceDesc.Streams[0], BlockTraceStreamServer_StreamBlockTraceData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Block]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockTraceStreamServer_StreamBlockTraceDataClient = grpc.ServerStreamingClient[Block]

// BlockTraceStreamServerServer is the server API for BlockTraceStreamServer service.
// All implementations must embed UnimplementedBlockTraceStreamServerServer
// for forward compatibility.
//
// gRPC service definition
type BlockTraceStreamServerServer interface {
	StreamBlockTraceData(*StreamRequest, grpc.ServerStreamingServer[Block]) error
	mustEmbedUnimplementedBlockTraceStreamServerServer()
}

// UnimplementedBlockTraceStreamServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlockTraceStreamServerServer struct{}

func (UnimplementedBlockTraceStreamServerServer) StreamBlockTraceData(*StreamRequest, grpc.ServerStreamingServer[Block]) error {
	return status.Errorf(codes.Unimplemented, "method StreamBlockTraceData not implemented")
}
func (UnimplementedBlockTraceStreamServerServer) mustEmbedUnimplementedBlockTraceStreamServerServer() {
}
func (UnimplementedBlockTraceStreamServerServer) testEmbeddedByValue() {}

// UnsafeBlockTraceStreamServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockTraceStreamServerServer will
// result in compilation errors.
type UnsafeBlockTraceStreamServerServer interface {
	mustEmbedUnimplementedBlockTraceStreamServerServer()
}

func RegisterBlockTraceStreamServerServer(s grpc.ServiceRegistrar, srv BlockTraceStreamServerServer) {
	// If the following call pancis, it indicates UnimplementedBlockTraceStreamServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlockTraceStreamServer_ServiceDesc, srv)
}

func _BlockTraceStreamServer_StreamBlockTraceData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlockTraceStreamServerServer).StreamBlockTraceData(m, &grpc.GenericServerStream[StreamRequest, Block]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlockTraceStreamServer_StreamBlockTraceDataServer = grpc.ServerStreamingServer[Block]

// BlockTraceStreamServer_ServiceDesc is the grpc.ServiceDesc for BlockTraceStreamServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockTraceStreamServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.bloxroute.bsc.mev.blocktrace.BlockTraceStreamServer",
	HandlerType: (*BlockTraceStreamServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBlockTraceData",
			Handler:       _BlockTraceStreamServer_StreamBlockTraceData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blocktrace.proto",
}
