// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: blocktrace.proto

package blocktrace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Main Block
type Block struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Hash                string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header              *Header                `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	FutureValidatorInfo []*ValidatorInfo       `protobuf:"bytes,3,rep,name=future_validator_info,json=futureValidatorInfo,proto3" json:"future_validator_info,omitempty"`
	Transactions        []*Transaction         `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Withdrawals         []*Withdrawal          `protobuf:"bytes,5,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	Uncles              []string               `protobuf:"bytes,6,rep,name=uncles,proto3" json:"uncles,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blocktrace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetFutureValidatorInfo() []*ValidatorInfo {
	if x != nil {
		return x.FutureValidatorInfo
	}
	return nil
}

func (x *Block) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *Block) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

func (x *Block) GetUncles() []string {
	if x != nil {
		return x.Uncles
	}
	return nil
}

// Header
type Header struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ParentHash            string                 `protobuf:"bytes,1,opt,name=parentHash,proto3" json:"parentHash,omitempty"`
	Sha3Uncles            string                 `protobuf:"bytes,2,opt,name=sha3Uncles,proto3" json:"sha3Uncles,omitempty"`
	Miner                 string                 `protobuf:"bytes,3,opt,name=miner,proto3" json:"miner,omitempty"`
	StateRoot             string                 `protobuf:"bytes,4,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	TransactionsRoot      string                 `protobuf:"bytes,5,opt,name=transactionsRoot,proto3" json:"transactionsRoot,omitempty"`
	ReceiptsRoot          string                 `protobuf:"bytes,6,opt,name=receiptsRoot,proto3" json:"receiptsRoot,omitempty"`
	LogsBloom             string                 `protobuf:"bytes,7,opt,name=logsBloom,proto3" json:"logsBloom,omitempty"`
	Difficulty            string                 `protobuf:"bytes,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Number                string                 `protobuf:"bytes,9,opt,name=number,proto3" json:"number,omitempty"`
	GasLimit              string                 `protobuf:"bytes,10,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed               string                 `protobuf:"bytes,11,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Timestamp             string                 `protobuf:"bytes,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData             string                 `protobuf:"bytes,13,opt,name=extraData,proto3" json:"extraData,omitempty"`
	MixHash               string                 `protobuf:"bytes,14,opt,name=mixHash,proto3" json:"mixHash,omitempty"`
	Nonce                 string                 `protobuf:"bytes,15,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BlobGasUsed           string                 `protobuf:"bytes,16,opt,name=blobGasUsed,proto3" json:"blobGasUsed,omitempty"`
	ExcessBlobGas         string                 `protobuf:"bytes,17,opt,name=excessBlobGas,proto3" json:"excessBlobGas,omitempty"`
	ParentBeaconBlockRoot string                 `protobuf:"bytes,18,opt,name=parentBeaconBlockRoot,proto3" json:"parentBeaconBlockRoot,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_blocktrace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *Header) GetSha3Uncles() string {
	if x != nil {
		return x.Sha3Uncles
	}
	return ""
}

func (x *Header) GetMiner() string {
	if x != nil {
		return x.Miner
	}
	return ""
}

func (x *Header) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *Header) GetTransactionsRoot() string {
	if x != nil {
		return x.TransactionsRoot
	}
	return ""
}

func (x *Header) GetReceiptsRoot() string {
	if x != nil {
		return x.ReceiptsRoot
	}
	return ""
}

func (x *Header) GetLogsBloom() string {
	if x != nil {
		return x.LogsBloom
	}
	return ""
}

func (x *Header) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Header) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Header) GetGasLimit() string {
	if x != nil {
		return x.GasLimit
	}
	return ""
}

func (x *Header) GetGasUsed() string {
	if x != nil {
		return x.GasUsed
	}
	return ""
}

func (x *Header) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Header) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *Header) GetMixHash() string {
	if x != nil {
		return x.MixHash
	}
	return ""
}

func (x *Header) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Header) GetBlobGasUsed() string {
	if x != nil {
		return x.BlobGasUsed
	}
	return ""
}

func (x *Header) GetExcessBlobGas() string {
	if x != nil {
		return x.ExcessBlobGas
	}
	return ""
}

func (x *Header) GetParentBeaconBlockRoot() string {
	if x != nil {
		return x.ParentBeaconBlockRoot
	}
	return ""
}

// Validator Info
type ValidatorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   uint64                 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Accessible    bool                   `protobuf:"varint,3,opt,name=accessible,proto3" json:"accessible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorInfo) Reset() {
	*x = ValidatorInfo{}
	mi := &file_blocktrace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorInfo) ProtoMessage() {}

func (x *ValidatorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorInfo.ProtoReflect.Descriptor instead.
func (*ValidatorInfo) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorInfo) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *ValidatorInfo) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ValidatorInfo) GetAccessible() bool {
	if x != nil {
		return x.Accessible
	}
	return false
}

// Transaction
type Transaction struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	From          string                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Gas           string                  `protobuf:"bytes,2,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      string                  `protobuf:"bytes,3,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Hash          string                  `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Input         string                  `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Nonce         string                  `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Value         string                  `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	V             string                  `protobuf:"bytes,8,opt,name=v,proto3" json:"v,omitempty"`
	R             string                  `protobuf:"bytes,9,opt,name=r,proto3" json:"r,omitempty"`
	S             string                  `protobuf:"bytes,10,opt,name=s,proto3" json:"s,omitempty"`
	To            string                  `protobuf:"bytes,11,opt,name=to,proto3" json:"to,omitempty"`
	Status        int32                   `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	Logs          []*Log                  `protobuf:"bytes,13,rep,name=logs,proto3" json:"logs,omitempty"`
	StateDiff     map[string]*StateChange `protobuf:"bytes,14,rep,name=stateDiff,proto3" json:"stateDiff,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // State changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_blocktrace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{3}
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *Transaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transaction) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Transaction) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *Transaction) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *Transaction) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *Transaction) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Transaction) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *Transaction) GetStateDiff() map[string]*StateChange {
	if x != nil {
		return x.StateDiff
	}
	return nil
}

type StateChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         map[string]string      `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateChange) Reset() {
	*x = StateChange{}
	mi := &file_blocktrace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateChange) ProtoMessage() {}

func (x *StateChange) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateChange.ProtoReflect.Descriptor instead.
func (*StateChange) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{4}
}

func (x *StateChange) GetSlots() map[string]string {
	if x != nil {
		return x.Slots
	}
	return nil
}

// Log
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_blocktrace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{5}
}

func (x *Log) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Log) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Log) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Withdrawal
type Withdrawal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	ValidatorIndex string                 `protobuf:"bytes,2,opt,name=validatorIndex,proto3" json:"validatorIndex,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Amount         string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_blocktrace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{6}
}

func (x *Withdrawal) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Withdrawal) GetValidatorIndex() string {
	if x != nil {
		return x.ValidatorIndex
	}
	return ""
}

func (x *Withdrawal) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Withdrawal) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestData   string                 `protobuf:"bytes,1,opt,name=request_data,json=requestData,proto3" json:"request_data,omitempty"` // defaults to "block_stream"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_blocktrace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blocktrace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_blocktrace_proto_rawDescGZIP(), []int{7}
}

func (x *StreamRequest) GetRequestData() string {
	if x != nil {
		return x.RequestData
	}
	return ""
}

var File_blocktrace_proto protoreflect.FileDescriptor

const file_blocktrace_proto_rawDesc = "" +
	"\n" +
	"\x10blocktrace.proto\x12 com.bloxroute.bsc.mev.blocktrace\"\xfd\x02\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12@\n" +
	"\x06header\x18\x02 \x01(\v2(.com.bloxroute.bsc.mev.blocktrace.HeaderR\x06header\x12c\n" +
	"\x15future_validator_info\x18\x03 \x03(\v2/.com.bloxroute.bsc.mev.blocktrace.ValidatorInfoR\x13futureValidatorInfo\x12Q\n" +
	"\ftransactions\x18\x04 \x03(\v2-.com.bloxroute.bsc.mev.blocktrace.TransactionR\ftransactions\x12N\n" +
	"\vwithdrawals\x18\x05 \x03(\v2,.com.bloxroute.bsc.mev.blocktrace.WithdrawalR\vwithdrawals\x12\x16\n" +
	"\x06uncles\x18\x06 \x03(\tR\x06uncles\"\xc2\x04\n" +
	"\x06Header\x12\x1e\n" +
	"\n" +
	"parentHash\x18\x01 \x01(\tR\n" +
	"parentHash\x12\x1e\n" +
	"\n" +
	"sha3Uncles\x18\x02 \x01(\tR\n" +
	"sha3Uncles\x12\x14\n" +
	"\x05miner\x18\x03 \x01(\tR\x05miner\x12\x1c\n" +
	"\tstateRoot\x18\x04 \x01(\tR\tstateRoot\x12*\n" +
	"\x10transactionsRoot\x18\x05 \x01(\tR\x10transactionsRoot\x12\"\n" +
	"\freceiptsRoot\x18\x06 \x01(\tR\freceiptsRoot\x12\x1c\n" +
	"\tlogsBloom\x18\a \x01(\tR\tlogsBloom\x12\x1e\n" +
	"\n" +
	"difficulty\x18\b \x01(\tR\n" +
	"difficulty\x12\x16\n" +
	"\x06number\x18\t \x01(\tR\x06number\x12\x1a\n" +
	"\bgasLimit\x18\n" +
	" \x01(\tR\bgasLimit\x12\x18\n" +
	"\agasUsed\x18\v \x01(\tR\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\tR\ttimestamp\x12\x1c\n" +
	"\textraData\x18\r \x01(\tR\textraData\x12\x18\n" +
	"\amixHash\x18\x0e \x01(\tR\amixHash\x12\x14\n" +
	"\x05nonce\x18\x0f \x01(\tR\x05nonce\x12 \n" +
	"\vblobGasUsed\x18\x10 \x01(\tR\vblobGasUsed\x12$\n" +
	"\rexcessBlobGas\x18\x11 \x01(\tR\rexcessBlobGas\x124\n" +
	"\x15parentBeaconBlockRoot\x18\x12 \x01(\tR\x15parentBeaconBlockRoot\"o\n" +
	"\rValidatorInfo\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x04R\vblockHeight\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1e\n" +
	"\n" +
	"accessible\x18\x03 \x01(\bR\n" +
	"accessible\"\xfb\x03\n" +
	"\vTransaction\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x10\n" +
	"\x03gas\x18\x02 \x01(\tR\x03gas\x12\x1a\n" +
	"\bgasPrice\x18\x03 \x01(\tR\bgasPrice\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x14\n" +
	"\x05input\x18\x05 \x01(\tR\x05input\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\x12\x14\n" +
	"\x05value\x18\a \x01(\tR\x05value\x12\f\n" +
	"\x01v\x18\b \x01(\tR\x01v\x12\f\n" +
	"\x01r\x18\t \x01(\tR\x01r\x12\f\n" +
	"\x01s\x18\n" +
	" \x01(\tR\x01s\x12\x0e\n" +
	"\x02to\x18\v \x01(\tR\x02to\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x129\n" +
	"\x04logs\x18\r \x03(\v2%.com.bloxroute.bsc.mev.blocktrace.LogR\x04logs\x12Z\n" +
	"\tstateDiff\x18\x0e \x03(\v2<.com.bloxroute.bsc.mev.blocktrace.Transaction.StateDiffEntryR\tstateDiff\x1ak\n" +
	"\x0eStateDiffEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.com.bloxroute.bsc.mev.blocktrace.StateChangeR\x05value:\x028\x01\"\x97\x01\n" +
	"\vStateChange\x12N\n" +
	"\x05slots\x18\x01 \x03(\v28.com.bloxroute.bsc.mev.blocktrace.StateChange.SlotsEntryR\x05slots\x1a8\n" +
	"\n" +
	"SlotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x03Log\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"|\n" +
	"\n" +
	"Withdrawal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12&\n" +
	"\x0evalidatorIndex\x18\x02 \x01(\tR\x0evalidatorIndex\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"2\n" +
	"\rStreamRequest\x12!\n" +
	"\frequest_data\x18\x01 \x01(\tR\vrequestData2\x8c\x01\n" +
	"\x16BlockTraceStreamServer\x12r\n" +
	"\x14StreamBlockTraceData\x12/.com.bloxroute.bsc.mev.blocktrace.StreamRequest\x1a'.com.bloxroute.bsc.mev.blocktrace.Block0\x01B7Z5github.com/bloXroute-Labs/bsc-mev-proto/go/blocktraceb\x06proto3"

var (
	file_blocktrace_proto_rawDescOnce sync.Once
	file_blocktrace_proto_rawDescData []byte
)

func file_blocktrace_proto_rawDescGZIP() []byte {
	file_blocktrace_proto_rawDescOnce.Do(func() {
		file_blocktrace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blocktrace_proto_rawDesc), len(file_blocktrace_proto_rawDesc)))
	})
	return file_blocktrace_proto_rawDescData
}

var file_blocktrace_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_blocktrace_proto_goTypes = []any{
	(*Block)(nil),         // 0: com.bloxroute.bsc.mev.blocktrace.Block
	(*Header)(nil),        // 1: com.bloxroute.bsc.mev.blocktrace.Header
	(*ValidatorInfo)(nil), // 2: com.bloxroute.bsc.mev.blocktrace.ValidatorInfo
	(*Transaction)(nil),   // 3: com.bloxroute.bsc.mev.blocktrace.Transaction
	(*StateChange)(nil),   // 4: com.bloxroute.bsc.mev.blocktrace.StateChange
	(*Log)(nil),           // 5: com.bloxroute.bsc.mev.blocktrace.Log
	(*Withdrawal)(nil),    // 6: com.bloxroute.bsc.mev.blocktrace.Withdrawal
	(*StreamRequest)(nil), // 7: com.bloxroute.bsc.mev.blocktrace.StreamRequest
	nil,                   // 8: com.bloxroute.bsc.mev.blocktrace.Transaction.StateDiffEntry
	nil,                   // 9: com.bloxroute.bsc.mev.blocktrace.StateChange.SlotsEntry
}
var file_blocktrace_proto_depIdxs = []int32{
	1, // 0: com.bloxroute.bsc.mev.blocktrace.Block.header:type_name -> com.bloxroute.bsc.mev.blocktrace.Header
	2, // 1: com.bloxroute.bsc.mev.blocktrace.Block.future_validator_info:type_name -> com.bloxroute.bsc.mev.blocktrace.ValidatorInfo
	3, // 2: com.bloxroute.bsc.mev.blocktrace.Block.transactions:type_name -> com.bloxroute.bsc.mev.blocktrace.Transaction
	6, // 3: com.bloxroute.bsc.mev.blocktrace.Block.withdrawals:type_name -> com.bloxroute.bsc.mev.blocktrace.Withdrawal
	5, // 4: com.bloxroute.bsc.mev.blocktrace.Transaction.logs:type_name -> com.bloxroute.bsc.mev.blocktrace.Log
	8, // 5: com.bloxroute.bsc.mev.blocktrace.Transaction.stateDiff:type_name -> com.bloxroute.bsc.mev.blocktrace.Transaction.StateDiffEntry
	9, // 6: com.bloxroute.bsc.mev.blocktrace.StateChange.slots:type_name -> com.bloxroute.bsc.mev.blocktrace.StateChange.SlotsEntry
	4, // 7: com.bloxroute.bsc.mev.blocktrace.Transaction.StateDiffEntry.value:type_name -> com.bloxroute.bsc.mev.blocktrace.StateChange
	7, // 8: com.bloxroute.bsc.mev.blocktrace.BlockTraceStreamServer.StreamBlockTraceData:input_type -> com.bloxroute.bsc.mev.blocktrace.StreamRequest
	0, // 9: com.bloxroute.bsc.mev.blocktrace.BlockTraceStreamServer.StreamBlockTraceData:output_type -> com.bloxroute.bsc.mev.blocktrace.Block
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_blocktrace_proto_init() }
func file_blocktrace_proto_init() {
	if File_blocktrace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blocktrace_proto_rawDesc), len(file_blocktrace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blocktrace_proto_goTypes,
		DependencyIndexes: file_blocktrace_proto_depIdxs,
		MessageInfos:      file_blocktrace_proto_msgTypes,
	}.Build()
	File_blocktrace_proto = out.File
	file_blocktrace_proto_goTypes = nil
	file_blocktrace_proto_depIdxs = nil
}
