// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.3
// source: config_updates_message.proto

package mevrelaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigUpdatesRequest message containing the request for configuration updates.
type ConfigUpdatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigUpdatesRequest) Reset() {
	*x = ConfigUpdatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_updates_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdatesRequest) ProtoMessage() {}

func (x *ConfigUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_updates_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdatesRequest.ProtoReflect.Descriptor instead.
func (*ConfigUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_config_updates_message_proto_rawDescGZIP(), []int{0}
}

// ConfigUpdatesResponse message containing the response to the configuration updates.
type ConfigUpdatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The update to the validator or builder configuration.
	//
	// Types that are assignable to Update:
	//	*ConfigUpdatesResponse_Validator
	//	*ConfigUpdatesResponse_Builder
	Update isConfigUpdatesResponse_Update `protobuf_oneof:"update"`
}

func (x *ConfigUpdatesResponse) Reset() {
	*x = ConfigUpdatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_updates_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigUpdatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdatesResponse) ProtoMessage() {}

func (x *ConfigUpdatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_updates_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdatesResponse.ProtoReflect.Descriptor instead.
func (*ConfigUpdatesResponse) Descriptor() ([]byte, []int) {
	return file_config_updates_message_proto_rawDescGZIP(), []int{1}
}

func (m *ConfigUpdatesResponse) GetUpdate() isConfigUpdatesResponse_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *ConfigUpdatesResponse) GetValidator() *ValidatorConfigUpdate {
	if x, ok := x.GetUpdate().(*ConfigUpdatesResponse_Validator); ok {
		return x.Validator
	}
	return nil
}

func (x *ConfigUpdatesResponse) GetBuilder() *BuilderConfigUpdate {
	if x, ok := x.GetUpdate().(*ConfigUpdatesResponse_Builder); ok {
		return x.Builder
	}
	return nil
}

type isConfigUpdatesResponse_Update interface {
	isConfigUpdatesResponse_Update()
}

type ConfigUpdatesResponse_Validator struct {
	// The validator configuration update.
	Validator *ValidatorConfigUpdate `protobuf:"bytes,1,opt,name=validator,proto3,oneof"`
}

type ConfigUpdatesResponse_Builder struct {
	// The builder configuration update.
	Builder *BuilderConfigUpdate `protobuf:"bytes,2,opt,name=builder,proto3,oneof"`
}

func (*ConfigUpdatesResponse_Validator) isConfigUpdatesResponse_Update() {}

func (*ConfigUpdatesResponse_Builder) isConfigUpdatesResponse_Update() {}

// Contains the current validator configurations.
type ValidatorConfigUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of validator configuration records.
	Records []*ValidatorConfigRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *ValidatorConfigUpdate) Reset() {
	*x = ValidatorConfigUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_updates_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorConfigUpdate) ProtoMessage() {}

func (x *ValidatorConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_config_updates_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorConfigUpdate.ProtoReflect.Descriptor instead.
func (*ValidatorConfigUpdate) Descriptor() ([]byte, []int) {
	return file_config_updates_message_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatorConfigUpdate) GetRecords() []*ValidatorConfigRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

// Represents a validator configuration record.
type ValidatorConfigRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Wallet address of the validator.
	ValidatorWalletAddress string `protobuf:"bytes,1,opt,name=validator_wallet_address,json=validatorWalletAddress,proto3" json:"validator_wallet_address,omitempty"`
	// The gas ceiling for the validator.
	GasCeil uint64 `protobuf:"varint,2,opt,name=gas_ceil,json=gasCeil,proto3" json:"gas_ceil,omitempty"`
}

func (x *ValidatorConfigRecord) Reset() {
	*x = ValidatorConfigRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_updates_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorConfigRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorConfigRecord) ProtoMessage() {}

func (x *ValidatorConfigRecord) ProtoReflect() protoreflect.Message {
	mi := &file_config_updates_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorConfigRecord.ProtoReflect.Descriptor instead.
func (*ValidatorConfigRecord) Descriptor() ([]byte, []int) {
	return file_config_updates_message_proto_rawDescGZIP(), []int{3}
}

func (x *ValidatorConfigRecord) GetValidatorWalletAddress() string {
	if x != nil {
		return x.ValidatorWalletAddress
	}
	return ""
}

func (x *ValidatorConfigRecord) GetGasCeil() uint64 {
	if x != nil {
		return x.GasCeil
	}
	return 0
}

// BuilderConfigUpdate message containing the builder configuration update.
type BuilderConfigUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Wallet address for payouts for MEV opportunities.
	PayoutWalletAddress string `protobuf:"bytes,1,opt,name=payout_wallet_address,json=payoutWalletAddress,proto3" json:"payout_wallet_address,omitempty"`
}

func (x *BuilderConfigUpdate) Reset() {
	*x = BuilderConfigUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_updates_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuilderConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuilderConfigUpdate) ProtoMessage() {}

func (x *BuilderConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_config_updates_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuilderConfigUpdate.ProtoReflect.Descriptor instead.
func (*BuilderConfigUpdate) Descriptor() ([]byte, []int) {
	return file_config_updates_message_proto_rawDescGZIP(), []int{4}
}

func (x *BuilderConfigUpdate) GetPayoutWalletAddress() string {
	if x != nil {
		return x.PayoutWalletAddress
	}
	return ""
}

var File_config_updates_message_proto protoreflect.FileDescriptor

var file_config_updates_message_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e,
	0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x78, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x62, 0x73,
	0x63, 0x2e, 0x6d, 0x65, 0x76, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x16,
	0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc9, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x55, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x78, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2e, 0x62, 0x73, 0x63, 0x2e, 0x6d, 0x65, 0x76, 0x2e, 0x72, 0x65, 0x6c, 0x61,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x09, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x62,
	0x6c, 0x6f, 0x78, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x62, 0x73, 0x63, 0x2e, 0x6d, 0x65, 0x76,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x22, 0x68, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4f, 0x0a, 0x07, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x78, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2e, 0x62, 0x73, 0x63,
	0x2e, 0x6d, 0x65, 0x76, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x6c, 0x0a, 0x15,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x38, 0x0a, 0x18, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x61, 0x73, 0x5f, 0x63, 0x65, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x67, 0x61, 0x73, 0x43, 0x65, 0x69, 0x6c, 0x22, 0x49, 0x0a, 0x13, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x32, 0x0a, 0x15, 0x70, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x5f, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x70, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x6f, 0x58, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2d, 0x4c, 0x61,
	0x62, 0x73, 0x2f, 0x62, 0x73, 0x63, 0x2d, 0x6d, 0x65, 0x76, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x76, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_updates_message_proto_rawDescOnce sync.Once
	file_config_updates_message_proto_rawDescData = file_config_updates_message_proto_rawDesc
)

func file_config_updates_message_proto_rawDescGZIP() []byte {
	file_config_updates_message_proto_rawDescOnce.Do(func() {
		file_config_updates_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_updates_message_proto_rawDescData)
	})
	return file_config_updates_message_proto_rawDescData
}

var file_config_updates_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_updates_message_proto_goTypes = []interface{}{
	(*ConfigUpdatesRequest)(nil),  // 0: com.bloxroute.bsc.mev.relay.v1.ConfigUpdatesRequest
	(*ConfigUpdatesResponse)(nil), // 1: com.bloxroute.bsc.mev.relay.v1.ConfigUpdatesResponse
	(*ValidatorConfigUpdate)(nil), // 2: com.bloxroute.bsc.mev.relay.v1.ValidatorConfigUpdate
	(*ValidatorConfigRecord)(nil), // 3: com.bloxroute.bsc.mev.relay.v1.ValidatorConfigRecord
	(*BuilderConfigUpdate)(nil),   // 4: com.bloxroute.bsc.mev.relay.v1.BuilderConfigUpdate
}
var file_config_updates_message_proto_depIdxs = []int32{
	2, // 0: com.bloxroute.bsc.mev.relay.v1.ConfigUpdatesResponse.validator:type_name -> com.bloxroute.bsc.mev.relay.v1.ValidatorConfigUpdate
	4, // 1: com.bloxroute.bsc.mev.relay.v1.ConfigUpdatesResponse.builder:type_name -> com.bloxroute.bsc.mev.relay.v1.BuilderConfigUpdate
	3, // 2: com.bloxroute.bsc.mev.relay.v1.ValidatorConfigUpdate.records:type_name -> com.bloxroute.bsc.mev.relay.v1.ValidatorConfigRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_updates_message_proto_init() }
func file_config_updates_message_proto_init() {
	if File_config_updates_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_updates_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigUpdatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_updates_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigUpdatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_updates_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorConfigUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_updates_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorConfigRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_updates_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuilderConfigUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_updates_message_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ConfigUpdatesResponse_Validator)(nil),
		(*ConfigUpdatesResponse_Builder)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_updates_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_updates_message_proto_goTypes,
		DependencyIndexes: file_config_updates_message_proto_depIdxs,
		MessageInfos:      file_config_updates_message_proto_msgTypes,
	}.Build()
	File_config_updates_message_proto = out.File
	file_config_updates_message_proto_rawDesc = nil
	file_config_updates_message_proto_goTypes = nil
	file_config_updates_message_proto_depIdxs = nil
}
